<?php

namespace Database\Seeders;

use App\Models\Activity;
use Illuminate\Database\Seeder;
use PHPUnit\Framework\Constraint\IsFalse;

class ActivitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Activity::factory()->count(5)->create();
        $a = Activity::create([
            'name'          => 'Walking',
            'season'        => 'winter,spring,summer,fall',
            'context'       => 'city,beach,lake,river,desert,countryside,forest',
            'is_indoor'     => true,
            'is_outdoor'    => true,
            'is_paid'       => false,
            'is_free'       => true,
            'training'      => false,  
            'companion'     => 'alone,partner,friends,family',        
        ]);
        $a->categories()->attach([1,3,4,10]);


        // 2
        $a = Activity::create([
            'name'          => 'Go to a concert',            
            'season'        => 'winter,spring,summer,fall',
            'context'       => 'city,countryside',
            'is_indoor'     => true,
            'is_outdoor'    => true,
            'is_paid'       => true,
            'is_free'       => false,
            'training'      => false,
            'companion'     => 'alone,partner,friends,family',           
        ]);
        $a->categories()->attach([1,3,5,20]);

        // 3
        $a = Activity::create([
            'name'          => 'Dress to impress',
            'season'        => 'winter,spring,summer,fall',
            'context'       => 'city',
            'is_indoor'     => true,
            'is_outdoor'    => true,
            'is_paid'       => true,
            'is_free'       => true,
            'training'      => true,
            'companion'     => 'alone,partner,friends,family',             
        ]);
        $a->categories()->attach([1,2,5,20]);

        // 4
        $a = Activity::create([
            'name'          => 'Shopping',
            'season'        => 'winter,spring,summer,fall',
            'context'       => 'city',
            'is_indoor'     => true,
            'is_outdoor'    => true,
            'is_paid'       => true,
            'is_free'       => false,
            'training'      => false,                   
        ]);
        $a->categories()->attach([3,5,20]);

        // 5
        $a = Activity::create([
            'name'          => 'Rock climbing',
            'season'        => 'spring,summer,fall',
            'context'       => 'mountain',
            'is_indoor'     => false,
            'is_outdoor'    => true,
            'is_paid'       => true,
            'is_free'       => true,
            'training'      => true,
            'companion'     => 'alone,partner,friends,family',                
        ]);
        $a->categories()->attach([4,20]);

        // 6
        $a = Activity::create([
            'name'          => 'Climbing',
            'season'        => 'winter,spring,summer,fall',
            'context'       => 'city, countryside',
            'is_indoor'     => false,
            'is_outdoor'    => true,
            'is_paid'       => true,
            'is_free'       => false,
            'training'      => true, 
            'companion'     => 'alone,partner,friends,family',            
        ]);
        $a->categories()->attach([4, 20]);

        // 7
        $a = Activity::create([
            'name'          => 'Make contribution',        
            'season'        => 'winter,spring,summer,fall',
            'context'       => 'city,mountain,beach,lake,river,desert,countryside,nature,forest',  
            'is_paid'       => true,
            'is_free'       => false,
            'is_indoor'     => true,
            'is_outdoor'    => true,
            'training'      => false,
            'companion'     => 'alone',      
        ]);
        $a->categories()->attach([21]);

        $a = Activity::create([
            'name'          => 'Read a Book',
            'season'        => 'winter,spring,summer,fall',
            'context'       => 'city,mountain,beach,lake,river,desert,countryside,nature,forest', 
            'is_paid'       => false,
            'is_free'       => true,
            'is_indoor'     => true,
            'is_outdoor'    => true,
            'training'      => false,  
            'companion'     => 'alone',             
        ]);
        $a->categories()->attach([3,5,10,17,18]);

        $a = Activity::create([
            'name'          => 'Camping',        
            'season'        => 'spring,summer,fall',
            'context'       => 'mountain,beach,lake,river,desert,countryside,nature,forest', 
            'is_paid'       => true,
            'is_free'       => true,
            'is_indoor'     => false,
            'is_outdoor'    => true,
            'training'      => false,
            'companion'     => 'partner,friends,family',              
        ]);
        $a->categories()->attach([1,4,5,7,10,11,12,17,20]);

        $a = Activity::create([
            'name'          => 'Drive a sport car',
            'season'        => 'winter,spring,summer,fall',
            'context'       => 'city,mountain,beach,lake,river,desert,countryside,nature,forest',  
            'is_paid'       => true,
            'is_free'       => false,
            'is_indoor'     => false,
            'is_outdoor'    => true,
            'training'      => true,
            'companion'     => 'alone',          
        ]);
        $a->categories()->attach([4,5,20,22]);

        $a = Activity::create([
            'name'          => 'Singing',        
            'season'        => 'winter,spring,summer,fall',
            'context'       => 'city,mountain,beach,lake,river,desert,countryside,nature,forest',  
            'is_paid'       => false,
            'is_free'       => true,
            'is_indoor'     => true,
            'is_outdoor'    => true,
            'training'      => true,
            'companion'     => 'alone',    
        ]);
        $a->categories()->attach([]);

        $a = Activity::create([
            'name'          => 'Writing',
            'season'        => 'winter,spring,summer,fall',
            'context'       => 'city,mountain,beach,lake,river,desert,countryside,nature,forest',        
            'is_paid'       => false,
            'is_free'       => true,
            'is_indoor'     => true,
            'is_outdoor'    => true,
            'training'      => true,
            'companion'     => 'alone',           
        ]);
        $a->categories()->attach([3,17,18,20,21]);

        $a = Activity::create([
            'name'          => 'Dancing',
            'season'        => 'winter,spring,summer,fall',
            'context'       => 'city, mountain,beach,lake,river,desert,countryside,nature,forest',          
            'is_paid'       => true,
            'is_free'       => true,
            'is_indoor'     => true,
            'is_outdoor'    => true,
            'training'      => true,
            'companion'     => 'alone,partner,friends',          
        ]);
        $a->categories()->attach([1,4,5,20]);

        $a = Activity::create([
            'name'          => 'Take pictures',        
            'is_paid'       => false,
            'is_free'       => true,
            'is_indoor'     => true,
            'is_outdoor'    => true,
            'training'      => true,
            'season'        => 'winter,spring,summer,fall',
            'context'       => 'city,mountain,beach,lake,river,desert,countryside,nature,forest',
            'companion'     => 'alone,partner,friends,family',    
        ]);
        $a->categories()->attach([1,3,5,18,20]);

        $a = Activity::create([
            'name'          => 'Ride a motorcycle',        
            'is_paid'       => true,
            'is_free'       => true,
            'is_indoor'     => false,
            'is_outdoor'    => true,
            'training'      => true,
            'season'        => 'winter,spring,summer,fall',
            'context'       => 'city,mountain,beach,lake,river,desert,countryside,nature,forest',
            'companion'     => 'alone,partner,friends',         
        ]);
        $a->categories()->attach([1,4,20]);

        $a = Activity::create([
            'name'          => 'Ride a snowmobile',        
            'is_paid'       => true,
            'is_free'       => false,
            'is_indoor'     => false,
            'is_outdoor'    => true,
            'training'      => true,
            'season'        => 'winter',
            'context'       => 'mountain,countryside,nature',
            'companion'     => 'alone,partner,friends',            
        ]);
        $a->categories()->attach([4, 20]);

        $a = Activity::create([
            'name'          => 'Ride a 4-wheeler',        
            'is_paid'       => true,
            'is_free'       => false,
            'is_indoor'     => false,
            'is_outdoor'    => true,
            'training'      => true,
            'season'        => 'winter,spring,summer,fall',
            'context'       => 'city,mountain,desert,countryside', 
            'companion'     => 'alone,partner,friends',           
        ]);
        $a->categories()->attach([4,20]);

        $a = Activity::create([
            'name'          => 'Ride a bycicle',        
            'is_paid'       => true,
            'is_free'       => true,
            'is_indoor'     => false,
            'is_outdoor'    => true,
            'training'      => true,
            'season'        => 'winter,spring,summer,fall',
            'context'       => 'city,mountain,beach,lake,river,desert,countryside',
            'companion'     => 'alone,partner,friends,family',           
        ]);
        $a->categories()->attach([1,4,5,20]);

        $a = Activity::create([
            'name'          => 'Hiking',        
            'is_paid'       => false,
            'is_free'       => true,
            'is_indoor'     => false,
            'is_outdoor'    => true,
            'training'      => false,
            'season'        => 'winter,spring,summer,fall',
            'context'       => 'mountain',
            'companion'     => 'alone,partner,friends,family',
        ]);
        $a->categories()->attach([1,4,7]);

        $a = Activity::create([
            'name'          => 'Woodwork',        
            'is_paid'       => true,
            'is_free'       => true,
            'is_indoor'     => true,
            'is_outdoor'    => true,
            'training'      => true,
            'season'        => 'winter,spring,summer,fall',
            'context'       => 'city,mountain,countryside,nature,forest',
            'companion'     => 'alone',          
        ]);
        $a->categories()->attach([3,24]);

        $a = Activity::create([
            'name'          => 'Horseback riding',        
            'is_paid'       => true,
            'is_free'       => false,
            'is_indoor'     => false,
            'is_outdoor'    => true,
            'training'      => true,
            'season'        => 'winter,spring,summer,fall',
            'context'       => 'city,countryside',  
            'companion'     => 'alone,partner,friends,family',          
        ]);
        $a->categories()->attach([1,4,5,7,20]);

        $a = Activity::create([
            'name'          => 'Wine tasting',        
            'is_paid'       => true,
            'is_free'       => true,
            'is_indoor'     => true,
            'is_outdoor'    => true,
            'training'      => true,
            'season'        => 'winter,spring,summer,fall',
            'context'       => 'city,countryside',
            'companion'     => 'alone,partner,friends',          
        ]);
        $a->categories()->attach([1,3,5,19]);

        $a = Activity::create([
            'name'          => 'Cook a special meal',        
            'is_paid'       => false,
            'is_free'       => true,
            'is_indoor'     => true,
            'is_outdoor'    => false,
            'training'      => true,
            'season'        => 'winter,spring,summer,fall',
            'context'       => '',
            'companion'     => 'alone,partner,friends,family',
        ]);
        $a->categories()->attach([1,19]);

        $a = Activity::create([
            'name'          => 'Read fiction novel',
            'is_paid'       => false,
            'is_free'       => true,
            'is_indoor'     => true,
            'is_outdoor'    => true,
            'training'      => true,
            'season'        => 'winter,spring,summer,fall',
            'context'       => '',
            'companion'     => 'alone',          
        ]);
        $a->categories()->attach([5,17,18]);

        $a = Activity::create([
            'name'          => 'Read a magazine',        
            'is_paid'       => false,
            'is_free'       => true,
            'is_indoor'     => true,
            'is_outdoor'    => true,
            'training'      => true,
            'season'        => 'winter,spring,summer,fall',
            'context'       => '',  
            'companion'     => 'alone',          
        ]);
        $a->categories()->attach([5,17,18]);

        $a = Activity::create([
            'name'          => 'Boat ride',        
            'is_paid'       => true,
            'is_free'       => true,
            'is_indoor'     => false,
            'is_outdoor'    => true,
            'training'      => true,
            'season'        => 'winter,spring,summer,fall',
            'context'       => 'beach',            
        ]);
        $a->categories()->attach([1,4,20,22]);

        $a = Activity::create([
            'name'          => 'Write your journal',        
            'is_paid'       => false,
            'is_free'       => true,
            'is_indoor'     => true,
            'is_outdoor'    => true,
            'training'      => true,
            'season'        => 'winter,spring,summer,fall',
            'context'       => '',            
        ]);
        $a->categories()->attach([]);
        
        $a = Activity::create([
            'name'          => 'Write music lyrics',        
            'is_paid'       => false,
            'is_free'       => true,
            'is_indoor'     => true,
            'is_outdoor'    => true,
            'training'      => true,
            'season'        => 'winter,spring,summer,fall',
            'context'       => '',   
            'companion'     => 'alone',         
        ]);
        $a->categories()->attach([20,24]);

        $a = Activity::create([
            'name'          => 'Running',        
            'is_paid'       => false,
            'is_free'       => true,
            'is_indoor'     => true,
            'is_outdoor'    => true,
            'training'      => true,
            'season'        => 'winter,spring,summer,fall',
            'context'       => 'city,nature',            
            'companion'     => 'alone',
        ]);
        $a->categories()->attach([4]);

        $a = Activity::create([
            'name'          => 'Jogging',        
            'is_paid'       => false,
            'is_free'       => true,
            'is_indoor'     => true,
            'is_outdoor'    => true,
            'training'      => true,
            'season'        => 'winter,spring,summer,fall',
            'context'       => 'city,nature',            
            'companion'     => 'alone',
        ]);
        $a->categories()->attach([4]);

        $a = Activity::create([
            'name' => 'Getting involved in politics',        
            'is_paid' => false,
            'is_free' => true,
            'is_indoor' => true,
            'is_outdoor' => true,
            'training' => false,
            'season' => 'winter,spring,summer,fall',
            'context' => 'city',            
        ]);
        $a->categories()->attach([21]);

        $a = Activity::create([
            'name' => 'Restoring furniture',        
            'is_paid' => false,
            'is_free' => true,
            'is_indoor' => true,
            'is_outdoor' => true,
            'training' => true,
            'season' => 'winter,spring,summer,fall',
            'context' => 'house, city, workshop',            
        ]);
        $a->categories()->attach([5,26]);

        $a = Activity::create([
            'name' => 'Skiing',        
            'is_paid' => true,
            'is_free' => false,
            'is_indoor' => false,
            'is_outdoor' => true,
            'training' => false,
            'season' => 'winter',
            'context' => 'mountain',            
        ]);
        $a->categories()->attach([4,5,7]);

        $a = Activity::create([
            'name' => 'Going to the cinema',        
            'is_paid' => true,
            'is_free' => false,
            'is_indoor' => true,
            'is_outdoor' => false,
            'training' => false,
            'season' => 'winter,spring,summer,fall',
            'context' => 'city',            
        ]);
        $a->categories()->attach([1,3,5,20]);

        $a = Activity::create([
            'name' => 'Buying gifts',        
            'is_paid' => true,
            'is_free' => false,
            'is_indoor' => true,
            'is_outdoor' => true,
            'training' => false,
            'season' => 'winter,spring,summer,fall',
            'context' => 'City',            
        ]);
        $a->categories()->attach([21]);

        $a = Activity::create([
            'name' => 'Bowling',        
            'is_paid' => true,
            'is_free' => false,
            'is_indoor' => true,
            'is_outdoor' => false,
            'training' => true,
            'season' => 'winter,spring,summer,fall',
            'context' => 'city',            
        ]);
        $a->categories()->attach([5,20]);

        $a = Activity::create([
            'name' => 'Solving puzzles',        
            'is_paid' => false,
            'is_free' => true,
            'is_indoor' => true,
            'is_outdoor' => true,
            'training' => true,
            'season' => 'winter,spring,summer,fall',
            'context' => 'city, countryside',            
        ]);
        $a->categories()->attach([18,24]);

        $a = Activity::create([
            'name' => 'Apologizing',        
            'is_paid' => false,
            'is_free' => true,
            'is_indoor' => true,
            'is_outdoor' => true,
            'training' => false,
            'season' => 'winter,spring,summer,fall',            
        ]);
        $a->categories()->attach([17,25]);

        $a = Activity::create([
            'name' => 'Taking a nap',        
            'is_paid' => false,
            'is_free' => true,
            'is_indoor' => true,
            'is_outdoor' => true,
            'training' => false,
            'season' => 'winter,spring,summer,fall',
            'context' => '',            
        ]);
        $a->categories()->attach([11]);

        $a = Activity::create([
            'name' => 'Going to a museum',        
            'is_paid' => true,
            'is_free' => true,
            'is_indoor' => true,
            'is_outdoor' => false,
            'training' => false,
            'season' => 'winter,spring,summer,fall',
            'context' => 'city',            
        ]);
        $a->categories()->attach([1,3,10,18,25]);

        $a = Activity::create([
            'name' => 'Fishing',        
            'is_paid' => true,
            'is_free' => true,
            'is_indoor' => false,
            'is_outdoor' => true,
            'training' => true,
            'season' => 'winter,spring,summer,fall',
            'context' => 'river, lake, sea, ocean',            
        ]);
        $a->categories()->attach([4,5,11,19]);

        $a = Activity::create([
            'name' => 'Visiting the sick',        
            'is_paid' => false,
            'is_free' => true,
            'is_indoor' => true,
            'is_outdoor' => true,
            'training' => false,
            'season' => 'winter,spring,summer,fall',                      
        ]);
        $a->categories()->attach([21]);

        $a = Activity::create([
            'name' => 'Swimming',        
            'is_paid' => true,
            'is_free' => true,
            'is_indoor' => true,
            'is_outdoor' => true,
            'training' => true,
            'season' => 'winter,spring,summer,fall',
            'context' => 'city, lake, beach, river, sea, ocean',            
        ]);
        $a->categories()->attach([4,5]);

        $a = Activity::create([
            'name' => 'Glassblowing',        
            'is_paid' => true,
            'is_free' => true,
            'is_indoor' => true,
            'is_outdoor' => true,
            'training' => true,
            'season' => 'winter,spring,summer,fall', 
            'companion'     => 'alone,partner,friends,family',                         
        ]);
        $a->categories()->attach([3,5,18,24]);

        $a = Activity::create([
            'name' => 'Badminton',        
            'is_paid' => true,
            'is_free' => true,
            'is_indoor' => true,
            'is_outdoor' => true,
            'training' => true,
            'season' => 'winter,spring,summer,fall',
            'context' => 'city, club',            
        ]);
        $a->categories()->attach([4]);

        $a = Activity::create([
            'name' => 'Whale watching',        
            'is_paid' => true,
            'is_free' => false,
            'is_indoor' => false,
            'is_outdoor' => true,
            'training' => false,
            'season' => 'winter,spring,summer,fall',
            'context' => 'ocean',            
        ]);
        $a->categories()->attach([7,10,22]);

        $a = Activity::create([
            'name' => 'Gardening',        
            'is_paid' => false,
            'is_free' => true,
            'is_indoor' => false,
            'is_outdoor' => true,
            'training' => true,
            'season' => 'winter,spring,summer,fall',                        
        ]);
        $a->categories()->attach([7,21]);

        $a = Activity::create([
            'name' => 'Barbecue',        
            'is_paid' => true,
            'is_free' => false,
            'is_indoor' => false,
            'is_outdoor' => true,
            'training' => false,
            'season' => 'winter,spring,summer,fall',                        
        ]);
        $a->categories()->attach([5,18]);

        $a = Activity::create([
            'name' => 'Call an old friend',        
            'is_paid' => false,
            'is_free' => true,
            'is_indoor' => true,
            'is_outdoor' => true,
            'training' => false,
            'season' => 'winter,spring,summer,fall',                        
        ]);
        $a->categories()->attach([5,26]);

        $a = Activity::create([
            'name' => 'Organize your desk',        
            'is_paid' => false,
            'is_free' => true,
            'is_indoor' => true,
            'is_outdoor' => false,
            'training' => false,
            'season' => 'winter,spring,summer,fall',
            'context' => 'Work office, home',            
        ]);
        $a->categories()->attach([26]);

        $a = Activity::create([
            'name' => 'Organize your closet',        
            'is_paid' => false,
            'is_free' => true,
            'is_indoor' => true,
            'is_outdoor' => false,
            'training' => false,
            'season' => 'winter,spring,summer,fall',
            'context' => 'Work office, home',            
        ]);
        $a->categories()->attach([26]);

        $a = Activity::create([
            'name' => 'Organize your pantry',        
            'is_paid' => false,
            'is_free' => true,
            'is_indoor' => true,
            'is_outdoor' => false,
            'training' => false,
            'season' => 'winter,spring,summer,fall',
            'context' => 'home',            
        ]);
        $a->categories()->attach([26]);

        $a = Activity::create([
            'name' => 'Organize your garage',        
            'is_paid' => false,
            'is_free' => true,
            'is_indoor' => true,
            'is_outdoor' => false,
            'training' => false,
            'season' => 'winter,spring,summer,fall',
            'context' => 'home',            
        ]);
        $a->categories()->attach([26]);

        $a = Activity::create([
            'name' => 'Organize your basement',        
            'is_paid' => false,
            'is_free' => true,
            'is_indoor' => true,
            'is_outdoor' => false,
            'training' => false,
            'season' => 'winter,spring,summer,fall',
            'context' => 'home',            
        ]);
        $a->categories()->attach([26]);

        $a = Activity::create([
            'name' => 'Organize your attic',        
            'is_paid' => false,
            'is_free' => true,
            'is_indoor' => true,
            'is_outdoor' => false,
            'training' => false,
            'season' => 'winter,spring,summer,fall',
            'context' => 'home',            
        ]);
        $a->categories()->attach([26]);

        $a = Activity::create([
            'name' => 'Play an instrument',        
            'is_paid' => false,
            'is_free' => true,
            'is_indoor' => true,
            'is_outdoor' => false,
            'training' => false,
            'season' => 'winter,spring,summer,fall',
            'context' => 'home',            
        ]);
        $a->categories()->attach([5,10,18,20]);

        $a = Activity::create([
            'name' => 'Visit a friend',     
            'is_paid' => false,
            'is_free' => true,
            'is_indoor' => true,
            'is_outdoor' => false,
            'training' => false,
            'season' => 'winter,spring,summer,fall',
            'context' => 'home',            
        ]);
        $a->categories()->attach([5]);

        $a = Activity::create([
            'name'      => 'Visit your parents',     
            'is_paid' => false,
            'is_free' => true,
            'is_indoor' => true,
            'is_outdoor' => false,
            'training' => false,
            'season' => 'winter,spring,summer,fall',
            'context' => 'home',            
        ]);
        $a->categories()->attach([23]);
    }
}

// 1 Romance
// 3 Cultural
// 4 Sport
// 5 Leisure
// 7 Nature
// 10 Discovery
// 11 Well-being
// 12 Beach
// 17 Spirituality
// 18 Education
// 19 Gastronomy
// 20 Fun & Entertainment
// 21 Contribution
// 22 Adventure
// 23 Family
// 24 Art & Self-expression
// 25 Self-development
// 26 Duties





// [
//     'name' => '',        
//     'is_paid' => '',
//     'is_free' => '',
//     'is_indoor' => '',
//     'is_outdoor' => '',
//     'requires_trainning' => '',
//     'season' => 'winter,spring,summer,fall',
//     'context' => 'city, mountain, beach, lake, river, desert, countryside, nature, forest',
//     'companion' => 'none, partner, family, friends, best friend, collegues, mom, dad, son, daughter, old friend, stranger',
// ]



// 'Being with friends, parents, siblings, family',
// 'Watching, talking about, or participating in sports',
// 'Meeting a new friend',
// 'Taking a test when you know you are prepared',
// 'Planning trips',
// 'Going on vacations or trips',
// 'Being by the ocean',
// 'Being in the mountains',
// 'Decorating your home',
// 'Being naked',
// 'Going to races',
// 'Going to a bar',
// 'Going to a lecture',

// 'Breathing clean air',

// 'Sewing, crochet, knitting, needlework',
// 'Watching TV',
// 'Talking politics',


// 'Working on cars, motorcycles, bikes',
// 'Thinking about a good future',
// 'Playing games',
// 'Completing a difficult task',
// 'Completing a much anticipated task',
// 'Completing a reprehensible task',
// 'Laughing',
// '',
// 'Solving personal problems',
// 'Solving financial problems',
// 'Good grooming, yourself or others',
// 'Being at events that celebrate others',
// 'Playing tennis or golf',

// 'Playing with animals',
// 'Having open conversation',
// 'Work',
// 'Going to church',
// 'Going to social clubs',
// 'Going to a business convention',
// 'Being in an expensive car',
// 'Playing a musical instrument',
// 'Cooking',

// 'Wearing casual clothes',

// 'Canning, freezing, putting food away',
// 'Driving a scenic route',
// 'Being in the city',
// 'Taking a bath',
// 'Being with children/grandchildren',
// 'Playing pool',
// 'Doing crafts',
// 'Wearing perfume',
// 'Wearing makeup',
// 'Fixing my hair differently',
// 'Getting a hair cut and/or color',
// 'Designing things',


// 'Cheering for you team',
// 'Watching the deer or other wild animals',
// 'Having an original and creative idea',
// 'Learning new things',
// 'Gardening',

// 'Sitting in the sun',
// '',
// 'Being alone',
// 'Seeing good things happen to others',
// 'Going to a fair, zoo, amusement park',
// 'Talking about philosophy or religion',
// 'Planning and organizing anything',

// 'Organizing your finances',
// 'Organizing your day',
// 'Having a lively talk',
// 'Going on a date',

// 'Gambling',
// 'Smoking',
// 'Listening to the radio',
// 'Having friends over',
// 'Introducing friends to each other',
// 'Going to meetings',
// 'Getting a massage, foot rub, back rub',
// 'Getting letters, cards, notes',
// 'Watching the sky',
// 'Going on a picnic or to the park',
// '',
// 'Giving a speech or lecture',
// 'Collecting',
// 'Helping someone else',
// 'Talking about children or grandchildren',
// 'Hearing or telling a joke',
// 'Winning a bet',
// 'Beautiful scenery',
// 'Eating',
// 'Hunting or shooting',


// 'Being noticed as attractive',
// 'Counseling someone',
// 'Going to the gym',
// 'Being remembered by others',
// 'Complimenting someone else',
// 'Thinking about friends',
// 'Going to book club',
// 'Being nice to someone who mistreated you ',
// 'Being with family',
// 'Horseback riding',
// 'Daydreaming',
// 'Kicking leaves, pebbles, tin cans',
// 'Going to reunions',
// 'Kissing',
// 'Using time wisely',
// 'Impressing a superior',
// 'Feeling the present of a higher power',
// 'Doing something on your own',
// 'Crying for yourself',
// 'Coaching',
// 'Going out to eat',
// 'Flowers',
// 'Being invited out',
// 'Receiving honors',
// 'Having someone greet you as if they are genuinely happy to see you',
// 'Being agreed with',
// 'Getting up early',
// 'Peach and quiet',
// 'Keeping a diary ',
// 'Visiting friends',
// 'Giving a massage or back rub',
// 'Meditating',
// 'Helping others',
// 'Sleep',
// 'Doing heavy outdoor work',
// 'Reading the newspaper',
// '',
// 'Dreaming',

// 'Standing up for yourself',

// 'Walking barefoot',
// 'Playing Frisbee or catch',
// 'Doing housework',
// 'Baking',
// 'Listening to music',
// 'Sex',
// 'Being with someone you love',
// 'Sleeping in late',
// 'Starting a project',
// 'Going to the library or book store',
// 'Watching people',
// 'Selling things',

// 'Repairing things',
// 'Working with a team',
// 'Being in charge',
// 'Writing letters, card, notes',
// 'Going to a banquet',
// 'Playing in the sand or on the grass',
// 'Other people showing interest in what I am doing',
// 'Other people showing interest in something I said',
// 'Expressing love or affection',
// 'Slowly eating your favorite treat',
// 'Having coffee or tea',
// 'Taking care of plants',
// 'Taking a walk',
// 'Staying up late',
// 'Going to bed early',
// 'Problem solving an interesting or complex question',
// 'Discussing complex social issues',
// 'Going to auctions or garage sales',
// 'Getting a bargain',
// 'Doing volunteer work',
// 'Getting money',
// 'Hearing a good sermon',
// 'Winning',
// 'Teaching',
// 'Going to parties',
// 'Looking at the night sky',
// 'Going to a coffeehouse',
// 'Surfing the internet',
// 'Learning new computer programs or new apps',
// 'Playing video games',
// 'Test driving a new car',
// 'House hunting',
// 'Wearing frilly undergarments',
// 'Getting rid of things you don’t need anymore',
// 'Browsing through a pawn shop or antique store',
// 'Designing your dream home',
// 'Going to a pet store',
// 'Flirting',
// 'Being in a chat room',
// 'Going to the electronics store',
// 'Going to the hardware store',
// 'Going to a nursery',
// 'Watching your favorite television shows',
// 'Watching a provocative or interesting documentary',

// 'Going to a quiz or trivia night',
// 'Spending time in nature',
// 'Watching the clouds drift by',
// 'Debating',
// 'Painting my nails',
// 'Going ice skating, roller skating/blading',
// 'Scheduling a day with nothing to do',
// 'Giving positive feedback about something (e.g.writing a letter or email about good service)',
// 'Feeding the birds',
// 'Spending an evening with good friends',
// 'Making jams or preserves',
// 'Going out to dinner',

// 'Having a political discussion',
// 'Repairing things around the house',
// 'Washing my car',
// 'Watching TV, videos',
// 'Sending a loved one a card in the mail',
// 'Baking something to share with others (e.g.family, neighbours, friends, work colleagues)',
// 'Taking a sauna, spa or a steam bath',
// 'Having a video call with someone who lives faraway',
// 'Organising my wardrobe',
// 'Playing musical instruments',
// 'Going to the ballet or opera',
// 'Lighting scented candles, oils or incense',
// 'Spending time alone',
// 'Exercising',
// 'Putting up a framed picture or artwork',
// 'Flirting',
// 'Entertaining',
// 'Riding a motorbike',

// 'Going to the planetarium or observatory',
// 'Birdwatching',
// 'Doing something spontaneously',
// 'Going on a picnic',
// 'Having a warm drink',
// 'Massaging hand cream into my hands',
// 'Fantasising about the future',
// 'Laughing',
// 'Flying a plane',
// 'Playing tennis or badminton',
// 'Clearing my email inbox',
// 'Planting a terrarium',
// 'Playing lawn games (e.g. bowls, croquet, bocce)',
// 'Going to a party',
// 'Getting out of debt/paying debts',
// 'Seeing and/or showing photos',
// 'Going on a city tour',
// 'Going to an agricultural show',
// 'Jogging, walking',
// 'Going to home opens',
// 'Researching a topic of interest',
// 'Going to the beach',
// 'Redecorating',
// 'Volunteering for a cause I support',
// 'Smelling a flower',
// 'Opening the curtains and blinds to let light in',
// 'Going to the zoo or aquarium',
// 'Doing jigsaw puzzles',
// 'Donating old clothes or items to charity',
// 'Lying in the sun',
// 'Learning a magic trick',
// 'Talking on the phone',
// 'Listening to a podcast or radio show',
// 'Walking around my city and noticing architecture of buildings',
// 'Doing arts and crafts',
// 'Going on a ghost tour',
// 'Sketching, painting',
// 'Mowing the lawn',
// 'Going horseback riding',
// 'Doing the dishes',
// 'Sitting outside and listening to birds sing',
// 'Going to a free public lecture',
// 'Travelling to national parks',
// 'Going to a fair or fete',
// 'Playing cards',
// 'Putting moisturising cream on my face / body',
// 'Volunteering at an animal shelter',
// 'Re-watching a favourite movie',
// '',

// 'Playing volleyball',
// 'Going bike riding',
// 'Entering a competition',
// 'Doing crossword puzzles',
// 'Patting or cuddling my pet',

// 'Soaking in the bathtub',
// 'Having a treatment at a day spa (e.g. facial)',
// 'Putting extra effort in to my appearance',
// 'Playing golf',
// 'Doing a favour for someone',
// 'Building a bird house or feeder',
// 'Looking at pictures of beautiful scenery',
// 'Having family get-togethers',
// 'Listening to music',
// 'Learning a new language',
// 'Taking a free online class',
// 'Working',
// 'Washing my hair',
// 'Singing around the house',
// 'Flipping through old photo albums',
// 'Upcycling or creatively reusing old items',
// 'Going sailing',
// 'Stretching muscles',
// 'Maintaining a musical instrument (e.g.restringing guitar)',
// 'Playing soccer',
// 'Buying clothes',
// 'Going to the botanic gardens',
// 'Going to a scenic spot and enjoying the view',
// 'Going to the speedway',
// 'Snuggling up with a soft blanket',
// 'Listening to an audiobook',
// 'Going to see live stand-up comedy',
// 'Writing down a list of things I am grateful for',
// 'Maintaining an aquarium',
// 'Playing Frisbee',
// 'Teaching a special skill to someone else (e.g. knitting, woodworking, painting, language)',
// 'Playing chess (with a friend or at a local club)',
// 'Going to a games arcade',
// 'Jumping on a trampoline',
// 'Sending a text message to a friend',
// 'Going fishing',
// 'Doodling',
// 'Putting a vase of fresh flowers in my house',
// 'Participating in a protest I support',
// 'Going to a movie',
// 'Surfing, bodyboarding or stand up paddle boarding',
// 'Baking home-made bread',
// 'Walking barefoot on soft grass',
// 'Watching a movie marathon',
// 'Skipping/ jumping rope',
// 'Being physically intimate with someone I want to be close to',
// 'Going to karaoke',
// 'Wearing an outfit that makes me feel good',
// 'Cooking some meals to freeze for later',
// 'Hobbies (stamp collecting, model building, etc.)',
// 'Talking to an older relative and asking them questions about their life',
// 'Listening to classical music',
// 'Photography',
// 'Watching funny videos on YouTube',
// 'Doing something religious or spiritual (e.g. going to church, praying)',
// 'Seeing a movie at the drive-in or outdoor cinema',
// 'Making my bed with fresh sheets',
// 'Lifting weights',
// 'Early morning coffee and newspaper',
// 'Planning a themed party (e.g. costume, murder mystery)',
// 'Wearing comfortable clothes',
// 'Shining my shoes',
// 'Acting',
// 'Going swimming',
// 'De-cluttering',
// 'Going rock climbing',
// 'Whittling',
// 'Going on a ride at a theme park or fair',
// 'Arranging flowers',
// 'Going to the gym',
// 'Working on my car or bicycle',
// 'Juggling or learning to juggle',
// 'Contacting an old school friend',
// 'Calligraphy',
// 'Sleeping',
// 'Driving',
// 'Going crabbing',
// 'Playing with my pets',
// 'Abseiling',
// 'Going kayaking, canoeing or white-water rafting',
// 'Listening to the radio',
// 'Doing Sudoku',
// 'Planting vegetables or flowers',
// 'Walks on the riverfront/foreshore',
// 'Shooting pool or playing billiards',
// 'Getting an indoor plant',
// 'Surfing the internet',
// 'Doing embroidery, cross stitching',
// 'Browsing a hardware store',
// 'Donating blood',
// 'Buying books',
// 'Meditating',
// 'Training my pet to do a new trick',
// 'Planning a day’s activities',
// 'Waking up early, and getting ready at a leisurelypace',
// 'Going to a Bingo night',
// 'Playing ping pong / table tennis',
// 'Buying an ice-cream from an ice-cream truck',
// 'Going on a hot air balloon ride',
// 'Sightseeing',
// 'Organising my work space',
// 'Dangling my feet off a jetty',
// 'Writing (e.g. poems, articles, blog, books)',
// 'Dancing in the dark',
// 'Having an indoor picnic',
// 'Reading classic literature',
// 'Going on a date',
// 'Taking children places',

// 'Putting on perfume or cologne',
// 'Digging my toes in the sand',
// 'Hitting golf balls at a driving range',
// 'Reading magazines or newspapers',

// 'Sending a handwritten letter',
// 'Going snorkelling',
// 'Going hiking, bush walking',


// 'Soaking in the bathtub',
// 'Planning my career',
// 'Collecting things (coins, shells, etc.)',
// 'Going for a holiday',
// 'Recycling old items',
// 'Relaxing',
// 'Going on a date',
// 'Going to a movie',
// 'Jogging, walking',
// 'Listening to music',
// 'Thinking I have done a full day’s work',
// 'Recalling past parties',
// 'Buying household gadgets',
// 'Lying in the sun',
// 'Planning a career change',
// 'Laughing',
// 'Thinking about my past trips',
// 'Listening to others',
// 'Reading magazines or newspapers',
// 'Hobbies (stamp collecting, model building, etc.)',
// 'Spending an evening with good friends',
// 'Planning a day’s activities ',
// 'Meeting new people',
// 'Remembering beautiful scenery',
// 'Saving money',
// 'Gambling',
// 'Going to the gym, doing aerobics',
// 'Eating',
// 'Thinking how it will be when I finish school',
// 'Getting out of debt/paying debts',
// 'Practising karate, judo, yoga',
// 'Thinking about retirement',
// 'Repairing things around the house',
// 'Working on my car (bicycle)',
// 'Remembering the words and deeds of loving people',
// 'Wearing sexy clothes',
// 'Having quiet evenings',
// 'Taking care of my plants',
// 'Buying, selling stocks and shares',
// 'Going swimming',
// 'Doodling',
// 'Exercising',
// 'Collecting old things',
// 'Going to a party',
// 'Thinking about buying things',
// 'Playing golf',
// 'Playing soccer',
// 'Flying kites',
// 'Having discussions with friends',
// 'Having family get-togethers',
// 'Riding a motorbike',
// 'Sex',
// 'Playing squash',

// 'Singing around the house',
// 'Arranging flowers',
// 'Going to church, praying (practising religion)',
// 'Losing weight',
// 'Going to the beach',
// 'Thinking I’m an OK person',
// 'A day with nothing to do',
// 'Having class reunions',
// 'Going ice skating, roller skating/blading',
// 'Going sailing',
// 'ravelling abroad, interstate or within the state',
// 'Sketching, painting',
// 'Doing something spontaneously ',
// 'Doing embroidery, cross stitching',
// 'Sleeping',
// 'Driving',
// 'Entertaining',
// 'Going to clubs (garden, sewing, etc.)',
// 'Thinking about getting married',
// 'Going birdwatching',
// 'Singing with groups',
// 'Flirting',
// 'Playing musical instruments',
// 'Doing arts and crafts',
// 'Making a gift for someone',
// 'Buying CDs, tapes, records',
// 'Watching boxing, wrestling',
// 'Planning parties',
// 'Cooking, baking',
// 'Going hiking, bush walking',
// 'Writing books (poems, articles)',
// 'Sewing',
// 'Buying clothes',
// 'Working',
// 'Going out to dinner',
// 'Discussing books',
// 'Sightseeing',
// 'Gardening',
// 'Going to the beauty salon',
// 'Early morning coffee and newspaper',
// 'Playing tennis',
// 'Kissing',
// 'Watching my children (play)',
// 'Thinking I have a lot more going for me than most people',
// 'Going to plays and concerts',
// 'Daydreaming',
// 'Planning to go to TAFE or university',
// 'Going for a drive',
// 'Listening to a stereo',
// 'Refinishing furniture',
// 'Watching videos or DVDs',
// 'Making lists of tasks',
// 'Going bike riding',
// 'Walks on the riverfront/foreshore',
// 'Buying gifts',
// 'Travelling to national parks',
// 'Completing a task',
// 'Thinking about my achievements ',
// 'Going to a footy game (or rugby, soccer, basketball, etc.)',
// 'Eating gooey, fattening foods',
// 'Exchanging emails, chatting on the internet',
// 'Photography',
// 'Going fishing',
// 'Thinking about pleasant events',
// 'Staying on a diet',
// 'Star gazing',
// 'Flying a plane',
// 'Reading fiction',
// 'Acting',
// 'Being alone',
// 'Writing diary/journal entries or letters',
// 'Cleaning',
// 'Reading non-fiction',
// 'Taking children places',
// 'Dancing',
// 'Going on a picnic',
// 'Thinking “I did that pretty well” after doing something',
// 'Meditating',
// 'Playing volleyball',
// 'Having lunch with a friend',
// 'Going to the hills',
// 'Thinking about having a family',
// 'Thoughts about happy moments in my childhood',
// 'Splurging',
// 'Playing cards',
// 'Having a political discussion',
// 'Solving riddles mentally',
// 'Playing cricket',
// 'Seeing and/or showing photos or slides',
// 'Knitting/crocheting/quilting',
// 'Doing crossword puzzles',
// 'Shooting pool/Playing billiards',
// 'Dressing up and looking nice',
// 'Reflecting on how I’ve improved',
// 'Buying things for myself',
// 'Talking on the phone',
// 'Going to museums, art galleries',
// 'Thinking religious thoughts',
// 'Surfing the internet',
// 'Lighting candles',
// 'Listening to the radio ',
// 'Going crabbing or prawning',
// 'Having coffee at a cafe',
// 'Getting/giving a massage',
// 'Saying “I love you”',
// 'Thinking about my good qualities',
// 'Buying books',
// 'Having a spa, or sauna',
// 'Going skiing',
// 'Going canoeing or white-water rafting',
// 'Going bowling',
// 'Doing woodworking',
// 'Fantasising about the future',
// 'Doing ballet, jazz/tap dancing',
// 'Debating',
// 'Playing computer games',
// 'Having an aquarium',
// 'Erotica (sex books, movies)',

// 'Going rock climbing',
// 'Thinking about becoming active in the community',
// 'Doing something new',
// 'Making jigsaw puzzles',
// 'Thinking I’m a person who can cope',
// 'Playing with my pets',

// 'Rearranging the furniture in my house',
// 'Buying new furniture',
// 'Going window shopping ',



// General hobbies
// Indoors

// '3D printing',
// 'Acrobatics',
// 'Acting',
// 'Amateur radio',
// 'Animation',
// 'Aquascaping',
// 'Astrology',
// 'Baking',
// 'Baton twirling',
// 'Blogging',
// 'Board/tabletop games',
// 'Book discussion clubs',
// 'Book restoration',
// 'Bowling',
// 'Brazilian jiu-jitsu',
// 'Breadmaking',
// 'Building',
// 'Bullet journaling',
// 'Cabaret',
// 'Calligraphy[6]',
// 'Candle making[7]',
// 'Candy making',
// 'Car fixing & building',
// 'Card games',
// 'Cardistry',
// 'Cheesemaking',
// 'Cleaning',
// 'Clothesmaking',
// 'Coffee roasting',
// 'Collecting',
// 'Coloring[8]',
// 'Computer programming',
// 'Confectionery',
// 'Cooking',
// 'Cosplaying',
// 'Couponing',
// 'Craft',
// 'Creative writing',
// 'Crocheting',
// 'Cross-stitch',
// 'Crossword puzzles',
// 'Cryptography',
// 'Cue sports',
// 'Dance',
// 'Digital arts',
// 'Distro Hopping',
// 'DJing',
// 'Do it yourself',
// 'Drama',
// 'Drawing',
// 'Drink mixing',
// 'Drinking',
// 'Electronic games',
// 'Electronics',
// 'Embroidery',
// 'Experimenting',
// 'Fantasy sports',
// 'Fashion',
// 'Fashion design',
// 'Fishkeeping',
// 'Filmmaking',
// 'Flower arranging',
// 'Fly tying',
// 'Foreign language learning',
// 'Furniture building',
// 'Gaming (tabletop games and role-playing games)',
// 'Genealogy',
// 'Gingerbread house making',

// 'Graphic design',
// 'Gunsmithing',
// 'Gymnastics',
// 'Hacking',
// 'Herp keeping',
// 'Home improvement',
// 'Homebrewing',
// 'Houseplant care',
// 'Hula hooping',
// 'Humor',
// 'Hydroponics',
// 'Ice skating',
// 'Jewelry making',
// 'Jigsaw puzzles',
// 'Journaling',
// 'Juggling',
// 'Karaoke',
// 'Karate',
// 'Kendama',
// 'Knife making',
// 'Knitting',
// 'Knot tying',
// 'Kombucha brewing',
// 'Lace making',
// 'Lapidary',
// 'Leather crafting',
// 'Lego building',
// 'Listening to music',
// 'Listening to podcasts',
// 'Lock picking',
// 'Machining[40]',
// 'Macrame[41]',
// 'Magic[42]',
// 'Makeup',
// 'Mazes (indoor/outdoor)',
// 'Metalworking',
// 'Model building[43]',
// 'Model engineering',
// 'Nail art',
// 'Needlepoint',
// 'Origami[44]',
// 'Painting[45]',
// 'Palmistry',
// 'Pet adoption & fostering',
// 'Philately',
// 'Photography',
// 'Pilates',
// 'Playing musical instruments',
// 'Poi',
// 'Pole Dancing',
// 'Pottery[47]',
// 'Powerlifting',
// 'Practical jokes',
// 'Pressed flower craft',
// 'Puzzles[48]',
// 'Quilling',
// 'Quilting[49]',
// 'Quizzes',
// 'Radio-controlled model',
// 'Rail transport modeling',
// 'Rapping',
// 'Reading[50]',
// 'Refinishing',
// 'Reiki',
// 'Robot combat',
// 'Rubik\'s Cube[51]',
// 'Scrapbooking[52]',
// 'SCUBA Diving',
// 'Sculpting[53]',
// 'Sewing[54]',
// 'Shoemaking',
// 'Singing[55]',
// 'Sketching[19]',
// 'Skipping rope',
// 'Slot car',
// 'Soapmaking[56]',
// 'Social media',
// 'Spreadsheets',
// 'Stand-up comedy[57]',
// 'Stamp collecting',
// 'Table tennis',
// 'Tarot',
// 'Taxidermy[58]',
// 'Thrifting',
// 'Video editing',
// 'Video game developing',
// 'Video gaming[59]',
// 'Videography',
// 'Virtual reality',
// 'Watching movies[60]',
// 'Watching television',
// 'Waxing',
// 'Weaving',
// 'Webtooning',
// 'Weight training',
// 'Welding',
// 'Whittling',
// 'Wikipedia editing',
// 'Winemaking',
// 'Wood carving[61]',
// 'Woodworking[62]',
// 'Word searches',
// 'Worldbuilding[63]',
// 'Writing[64]',
// 'Yo-yoing[65]',
// 'Yoga[66]',
// 'Zumba',
// 'Outdoors',
// 'Air sports[67]',
// 'Airsoft',
// 'Amateur geology',
// 'Amusement park visiting',
// 'Archery[68]',
// 'Astronomy[69]',
// 'Backpacking',
// 'Badminton',
// 'BASE jumping[70]',
// 'Baseball[71]',
// 'Basketball[72]',
// 'Beekeeping[73]',
// 'Birdwatching[74]',
// 'Blacksmithing',
// 'BMX[75]',
// 'Board sports[76]',
// 'Bodybuilding[77]',
// 'Bonsai',
// 'Butterfly watching',
// 'Bus riding',

// 'Canoeing',
// 'Canyoning',
// 'Car riding',
// 'Caving',
// 'Composting',
// 'Cycling',
// 'Dowsing[78]',
// 'Driving[79]',
// 'Farming',
// 'Fishing[80]',
// 'Flag football[81]',
// 'Flower growing',
// 'Flying[82]',
// 'Flying disc',
// 'Foraging[83]',
// 'Fossicking',
// 'Freestyle football[84]',
// 'Gardening[85]',
// 'Geocaching[86]',
// 'Ghost hunting[87]',
// 'Gold prospecting',
// 'Graffiti[88]',
// 'Handball[89]',
// 'Herbalism',
// 'Herping',
// 'High-power rocketry',
// 'Hiking[90]',
// 'Hobby horsing',
// 'Hobby tunneling',
// 'Hooping[91]',
// 'Horseback riding',
// 'Hunting[92]',
// 'Inline skating[93]',
// 'Jogging[94]',
// 'Jumping rope',
// 'Kayaking[95]',
// 'Kite flying[96]',
// 'Kitesurfing[97]',
// 'Lacrosse[98]',
// 'LARPing[99]',
// 'Letterboxing[100]',
// 'Longboarding',
// 'Martial arts',
// 'Metal detecting[101]',
// 'Meteorology',
// 'Motor sports[102]',
// 'Mountain biking[103]',
// 'Mountaineering[104]',
// 'Museum visiting',
// 'Mushroom hunting/mycology[105]',
// 'Netball[106]',
// 'Nordic skating[107]',
// 'Orienteering[108]',
// 'Paintball[109]',
// 'Parkour[110]',
// 'Photography[111]',
// 'Podcast hosting',
// 'Polo[112]',
// 'Public transport riding',
// 'Rafting[113]',
// 'Railway journeys',
// 'Rappelling[114]',
// 'Road biking',
// 'Rock climbing[104]',
// 'Roller skating[115]',
// 'Rugby[116]',
// 'Running[94]',
// 'Radio-controlled model',
// 'Sailing[117]',
// 'Sand art[118]',
// 'Scouting',
// 'Scuba diving[119]',
// 'Sculling or rowing[120]',
// 'Shooting[121]',
// 'Shopping[122]',
// 'Shuffleboard',
// 'Skateboarding[123]',
// 'Skiing[124]',
// 'Skimboarding[125]',
// 'Skydiving[126]',
// 'Slacklining[127]',
// 'Snowboarding[124]',
// 'Snowmobiling',
// 'Snowshoeing',
// 'Soccer',
// 'Stone skipping[128]',
// 'Sun bathing',
// 'Surfing[129]',
// 'Survivalism',
// 'Swimming[130]',
// 'Taekwondo[131]',
// 'Tai chi[132]',
// 'Tennis',
// 'Topiary',
// 'Tourism',
// 'Thru-hiking',
// 'Trade fair visiting',
// 'Travel',
// 'Urban exploration[133]',
// 'Vacation',
// 'Vegetable farming',
// 'Videography',
// 'Vehicle restoration[134]',
// 'Walking',
// 'Water sports[135]',
// 'Educational hobbies',
// 'Astronomy',
// 'Biology',
// 'Chemistry',
// 'Electrochemistry',
// 'Geography',
// 'History',
// 'Mathematics',
// 'Psychology',
// 'Physics',
// 'Railway studies',
// 'Science and technology studies',
// 'Social studies',
// 'Sports science',
// 'Collection hobbies',
// 'Indoors',
// 'Action figure',
// 'Antiquing[136]',
// 'Ant-keeping',
// 'Art collecting[137]',
// 'Book collecting[138]',
// 'Button collecting',
// 'Cartophily (card collecting)[139]',
// 'Coin collecting[140]',
// 'Comic book collecting[141]',
// 'Deltiology (postcard collecting)[142]',
// 'Die-cast toy',
// 'Digital hoarding',
// 'Dolls',
// 'Element collecting[143]',
// 'Ephemera collecting',
// 'Fusilately (phonecard collecting)',
// 'Knife collecting',
// 'Lotology (lottery ticket collecting)',
// 'Movie and movie memorabilia collecting[144]',
// 'Fingerprint collecting',
// 'Perfume',
// 'Phillumeny',
// 'Pin (lapel)',
// 'Radio-controlled model',
// 'Rail transport modelling',
// 'Record collecting[145]',
// 'Rock tumbling',
// 'Scutelliphily',
// 'Shoes',
// 'Slot car',
// 'Sports memorabilia',
// 'Stamp collecting[146]',
// 'Stuffed toy collecting',
// 'Tea bag collecting',
// 'Ticket collecting',
// 'Toys',
// 'Transit map collecting',
// 'Video game collecting[147]',
// 'Vintage cars[148]',
// 'Vintage clothing',
// 'Vinyl Records',
// 'Outdoors',
// 'Antiquities[149]',
// 'Auto audiophilia[150]',
// 'Flower collecting and pressing[151]',
// 'Fossil hunting[152]',
// 'Insect collecting[153]',
// 'Magnet fishing',
// 'Metal detecting[154]',
// 'Mineral collecting[155]',
// 'Rock balancing[156]',
// 'Sea glass collecting[157]',
// 'Seashell collecting[158]',
// 'Stone collecting[159]',
// 'Competitive hobbies',
// 'Indoors',
// 'Animal fancy[160]',
// 'Axe throwing',
// 'Backgammon',

// 'Baton twirling[162]',
// 'Beauty pageants',
// 'Billiards[163]',
// 'Bowling[164]',
// 'Boxing[165]',
// 'Bridge[166]',
// 'Checkers (draughts)',
// 'Cheerleading[167]',
// 'Chess[168]',
// 'Color guard[169]',
// 'Cribbage',
// 'Curling[170]',
// 'Dancing[171]',
// 'Darts[172]',
// 'Debate[173]',
// 'Dominoes',
// 'Eating',
// 'Esports',
// 'Fencing[174]',
// 'Go[175]',
// 'Gymnastics[176]',
// 'Ice hockey[177]',
// 'Ice skating[178]',
// 'Judo[179]',
// 'Jujitsu',
// 'Kabaddi[180]',
// 'Knowledge/word games',
// 'Laser tag[181]',
// 'Longboarding',
// 'Mahjong[182]',
// 'Marbles[183]',
// 'Martial arts[184]',
// 'Model racing',
// 'Model United Nations',
// 'Poker[185]',
// 'Pole Dancing',
// 'Pool',
// 'Role-playing games',
// 'Shogi',
// 'Slot car racing[186]',
// 'Speedcubing',
// 'Sport stacking',
// 'Table football[187]',
// 'Table tennis[188]',
// 'Volleyball[189]',
// 'Weightlifting[190]',
// 'Wrestling',
// 'Outdoors',
// 'Airsoft[191]',
// 'Archery[68]',
// 'Association football[192]',
// 'Australian rules football[193]',
// 'Auto racing[194]',
// 'Baseball[195]',
// 'Beach volleyball[196]',
// 'Breakdancing[197]',
// 'Climbing[104]',
// 'Cricket[198]',
// 'Croquet',
// 'Cycling[199]',
// 'Disc golf[200]',
// 'Dog sport[201]',
// 'Equestrianism[202]',
// 'Exhibition drill[203]',
// 'Field hockey[204]',
// 'Figure skating[31]',
// 'Fishing[205]',
// 'Footbag[206]',
// 'Frisbee',
// 'Golfing[207]',
// 'Handball[89]',
// 'Horseback riding',
// 'Horseshoes',
// 'Iceboat racing',
// 'Jukskei[208]',
// 'Kart racing[209]',
// 'Knife throwing',
// 'Lacrosse',
// 'Longboarding',
// 'Long-distance running',
// 'Marching band',
// 'Model aircraft[210]',
// 'Orienteering',
// 'Pickleball',
// 'Powerboat racing',
// 'Quidditch',
// 'Race walking',
// 'Racquetball[211]',
// 'Radio-controlled car racing[212]',
// 'Roller derby[213]',
// 'Rugby league football[214]',
// 'Sculling or rowing',
// 'Shooting sport[215]',
// 'Skateboarding[216]',
// 'Skiing',
// 'Sled dog racing',
// 'Softball',
// 'Speed skating[31]',
// 'Squash[211]',
// 'Surfing[129]',
// 'Swimming[130]',
// 'Table tennis[188]',
// 'Tennis[217]',
// 'Tennis polo',
// 'Tether car',
// 'Tour skating[107]',
// 'Tourism',
// 'Trapshooting',
// 'Triathlon[218]',
// 'Ultimate frisbee[219]',
// 'Volleyball[196]',
// 'Water polo',
// 'Observation hobbies',
// 'Indoors',
// 'Fishkeeping',
// 'Learning',
// 'Meditation',
// 'Microscopy[220]',
// 'Reading[221]',
// 'Research',
// 'Shortwave listening[222]',
// 'Audiophile[223]',
// 'Outdoors',
// 'Aircraft spotting[224]',
// 'Amateur astronomy[69]',
// 'Birdwatching[74]',
// 'Bus spotting[225]',
// 'Geocaching[86]',
// 'Gongoozling[226]',
// 'Herping[227]',
// 'Hiking/backpacking',
// 'Meteorology[228]',
// 'Photography',
// 'Satellite watching',
// 'Trainspotting[229]',

